[workspace]

members = [
    "biostation",
    "hello-rs",
    "prussia_debug",
    "prussia_dma",
    "prussia_intc",
    "prussia_rt",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
lto = true
