[package]
name = "hello-rs"
version = "0.1.0"
authors = ["Dan Ravensloft <dan.ravensloft@gmail.com>"]
edition = "2018"

[dependencies]
panic-halt = "0.2.0"
prussia_bios = { path = "../prussia_bios" }
prussia_dma = { path = "../prussia_dma" }
prussia_rt = { path = "../prussia_rt" }
