name: Audit Prussia

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  actions: none
  attestations: none
  checks: none
  contents: none
  deployments: none
  id-token:  none
  issues: none
  repository-projects: none
  discussions: none
  packages: none
  pages: none
  pull-requests: none
  security-events: none
  statuses: none


jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        persist-credentials: false

    - name: Set up build env
      uses: ./.github/actions/setup-build-env

    - name: Audit checks
      uses: rustsec/audit-check@69366f33c96575abad1ee0dba8212993eecbe998
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
